# Generated by Django X.X on YYYY-MM-DD HH:MM

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timeslot_timetable'), # Make sure this matches your previous migration file
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Class',
        ),
    ]