# Generated by Django 5.2.3 on 2025-06-29 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_course_to_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.department'),
        ),
    ]
