# Generated by Django 5.2.3 on 2025-07-06 07:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_class_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('objects', core.models.HODManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HOD', 'HOD'), ('STUDENT', 'Student'), ('FACULTY', 'Faculty')], max_length=50),
        ),
    ]
